name: "Release"

on:
  push:
      tags:
          - "**"

jobs:
    build:
         name: "Release Build"
         runs-on: ubuntu-latest

         steps:
            - uses: actions/checkout@v2.0.0

            - name: Release
              run: echo "Release wird gebaut..."
